version: "3.5"
services:
  mongo:
    image: "mongo"
    container_name: mongo-container-prod
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./mongoData:/data/db

  api:
    image: base-api:1.0
    container_name: api-container-prod
    restart: always
    depends_on:
      - mongo
    command: yarn start
    ports:
      - "80:80"
    environment:
      NODE_ENV: "production"
    env_file:
      - .env
